SET(_CPS_FUTURE_REQUIRED_VARS  CPS_FUTURE_INCLUDE_DIR)

FIND_PATH(
	CPS_FUTURE_INCLUDE_DIR
	NAMES cps/future.h
    HINTS ${CPS_FUTURE_DIR}/include
)

SET(CPS_FUTURE_PROCESS_INCLUDES CPS_FUTURE_INCLUDE_DIR)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	CPS_FUTURE
	DEFAULT_MSG
	${_CPS_FUTURE_REQUIRED_VARS}
)

