SET(_ASIO_PROTOCOLS_REQUIRED_VARS  ASIO_PROTOCOLS_INCLUDE_DIR ASIO_PROTOCOLS_LIBRARY )

FIND_PATH(
	ASIO_PROTOCOLS_INCLUDE_DIR
	NAMES net/amqp.h
    HINTS ${ASIO_PROTOCOLS_DIR}/include
)

FIND_LIBRARY(
	ASIO_PROTOCOLS_LIBRARY
	NAMES asio-protocols
    HINTS ${ASIO_PROTOCOLS_DIR}/lib
)

SET(ASIO_PROTOCOLS_PROCESS_INCLUDES ASIO_PROTOCOLS_INCLUDE_DIR)
SET(ASIO_PROTOCOLS_PROCESS_LIBS ASIO_PROTOCOLS_LIBRARY)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	ASIO_PROTOCOLS
	DEFAULT_MSG
	${_ASIO_PROTOCOLS_REQUIRED_VARS}
)

